### ISSUE TITLE
[Internal Server Error] appears when starting biomania using docker image?

### ISSUE THREAD

**Issue by chaozhangGS** [batmen-lab/BioMANIA#8]
docker run -e LIB=squidpy  -e OPENAI_API_KEY=[xxxx]  -e GITHUB_TOKEN=[xx] -d -p 8181:3000  chatbotuibiomania/biomania-together:v1.1.12-squidpy-cuda12.6-ubuntu22.04
![image](https://github.com/user-attachments/assets/1bfd6bcf-a018-4c6f-b0d6-2d77f863f198)
```
2024-10-15 23:12:42 
2024-10-15 23:12:42 > ai-chatbot-starter@0.1.0 start
2024-10-15 23:12:42 > next start
2024-10-15 23:12:42 
2024-10-15 23:12:43   ▲ Next.js 13.5.6
2024-10-15 23:12:43   - Local:        http://localhost:3000
2024-10-15 23:12:43 
2024-10-15 23:12:43  ✓ Ready in 453ms
2024-10-15 23:12:46 [nltk_data] Error loading stopwords: <urlopen error [Errno 111]
2024-10-15 23:12:46 [nltk_data]     Connection refused>
2024-10-15 23:12:46 Traceback (most recent call last):
2024-10-15 23:12:46   File "/usr/local/lib/python3.10/dist-packages/nltk/corpus/util.py", line 84, in __load
2024-10-15 23:12:46     root = nltk.data.find(f"{self.subdir}/{zip_name}")
2024-10-15 23:12:46   File "/usr/local/lib/python3.10/dist-packages/nltk/data.py", line 579, in find
2024-10-15 23:12:46     raise LookupError(resource_not_found)
2024-10-15 23:12:46 LookupError: 
2024-10-15 23:12:46 **********************************************************************
2024-10-15 23:12:46   Resource stopwords not found.
2024-10-15 23:12:46   Please use the NLTK Downloader to obtain the resource:
2024-10-15 23:12:46 
2024-10-15 23:12:46   >>> import nltk
2024-10-15 23:12:46   >>> nltk.download('stopwords')
2024-10-15 23:12:46   
2024-10-15 23:12:46   For more information see: https://www.nltk.org/data.html
2024-10-15 23:12:46 
2024-10-15 23:12:46   Attempted to load corpora/stopwords.zip/stopwords/
2024-10-15 23:12:46 
2024-10-15 23:12:46   Searched in:
2024-10-15 23:12:46     - '/root/nltk_data'
2024-10-15 23:12:46     - '/usr/nltk_data'
2024-10-15 23:12:46     - '/usr/share/nltk_data'
2024-10-15 23:12:46     - '/usr/lib/nltk_data'
2024-10-15 23:12:46     - '/usr/share/nltk_data'
2024-10-15 23:12:46     - '/usr/local/share/nltk_data'
2024-10-15 23:12:46     - '/usr/lib/nltk_data'
2024-10-15 23:12:46     - '/usr/local/lib/nltk_data'
2024-10-15 23:12:46 **********************************************************************
2024-10-15 23:12:46 
2024-10-15 23:12:46 
2024-10-15 23:12:46 During handling of the above exception, another exception occurred:
2024-10-15 23:12:46 
2024-10-15 23:12:46 Traceback (most recent call last):
2024-10-15 23:12:46   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
2024-10-15 23:12:46     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2024-10-15 23:12:46   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
2024-10-15 23:12:46     __import__(pkg_name)
2024-10-15 23:12:46   File "/app/src/deploy/__init__.py", line 4, in <module>
2024-10-15 23:12:46     from . import model
2024-10-15 23:12:46   File "/app/src/deploy/model.py", line 36, in <module>
2024-10-15 23:12:46     stop_words = set(stopwords.words('english'))
2024-10-15 23:12:46   File "/usr/local/lib/python3.10/dist-packages/nltk/corpus/util.py", line 120, in __getattr__
2024-10-15 23:12:46     self.__load()
2024-10-15 23:12:46   File "/usr/local/lib/python3.10/dist-packages/nltk/corpus/util.py", line 86, in __load
2024-10-15 23:12:46     raise e
2024-10-15 23:12:46   File "/usr/local/lib/python3.10/dist-packages/nltk/corpus/util.py", line 81, in __load
2024-10-15 23:12:46     root = nltk.data.find(f"{self.subdir}/{self.__name}")
2024-10-15 23:12:46   File "/usr/local/lib/python3.10/dist-packages/nltk/data.py", line 579, in find
2024-10-15 23:12:46     raise LookupError(resource_not_found)
2024-10-15 23:12:46 LookupError: 
2024-10-15 23:12:46 **********************************************************************
2024-10-15 23:12:46   Resource stopwords not found.
2024-10-15 23:12:46   Please use the NLTK Downloader to obtain the resource:
2024-10-15 23:12:46 
2024-10-15 23:12:46   >>> import nltk
2024-10-15 23:12:46   >>> nltk.download('stopwords')
2024-10-15 23:12:46   
2024-10-15 23:12:46   For more information see: https://www.nltk.org/data.html
2024-10-15 23:12:46 
2024-10-15 23:12:46   Attempted to load corpora/stopwords
2024-10-15 23:12:46 
2024-10-15 23:12:46   Searched in:
2024-10-15 23:12:46     - '/root/nltk_data'
2024-10-15 23:12:46     - '/usr/nltk_data'
2024-10-15 23:12:46     - '/usr/share/nltk_data'
2024-10-15 23:12:46     - '/usr/lib/nltk_data'
2024-10-15 23:12:46     - '/usr/share/nltk_data'
2024-10-15 23:12:46     - '/usr/local/share/nltk_data'
2024-10-15 23:12:46     - '/usr/lib/nltk_data'
2024-10-15 23:12:46     - '/usr/local/lib/nltk_data'
2024-10-15 23:12:46 **********************************************************************
2024-10-15 23:12:46 
2024-10-15 23:13:46 [TypeError: fetch failed] { cause: [Error: AggregateError] }
2024-10-15 23:13:55 [TypeError: fetch failed] { cause: [Error: AggregateError] }
2024-10-15 23:14:05 [TypeError: fetch failed] { cause: [Error: AggregateError] }
2024-10-15 23:14:12 [TypeError: fetch failed] { cause: [Error: AggregateError] }
2024-10-15 23:14:13 [TypeError: fetch failed] { cause: [Error: AggregateError] }
2024-10-15 23:14:13 [TypeError: fetch failed] { cause: [Error: AggregateError] }
2024-10-15 23:14:14 [TypeError: fetch failed] { cause: [Error: AggregateError] }
2024-10-15 23:14:14 [TypeError: fetch failed] { cause: [Error: AggregateError] }
2024-10-15 23:14:14 [TypeError: fetch failed] { cause: [Error: AggregateError] }
2024-10-15 23:14:14 [TypeError: fetch failed] { cause: [Error: AggregateError] }
2024-10-15 23:14:15 [TypeError: fetch failed] { cause: [Error: AggregateError] }
2024-10-15 23:14:15 [TypeError: fetch failed] { cause: [Error: AggregateError] }
2024-10-15 23:14:15 [TypeError: fetch failed] { cause: [Error: AggregateError] }
2024-10-15 23:14:15 [TypeError: fetch failed] { cause: [Error: AggregateError] }
2024-10-15 23:14:15 [TypeError: fetch failed] { cause: [Error: AggregateError] }
2024-10-15 23:14:16 [TypeError: fetch failed] { cause: [Error: AggregateError] }
2024-10-15 23:14:16 [TypeError: fetch failed] { cause: [Error: AggregateError] }
2024-10-15 23:14:16 [TypeError: fetch failed] { cause: [Error: AggregateError] }
2024-10-15 23:14:16 [TypeError: fetch failed] { cause: [Error: AggregateError] }
2024-10-15 23:14:16 [TypeError: fetch failed] { cause: [Error: AggregateError] }
2024-10-15 23:14:16 [TypeError: fetch failed] { cause: [Error: AggregateError] }
2024-10-15 23:14:16 [TypeError: fetch failed] { cause: [Error: AggregateError] }
2024-10-15 23:14:18 [TypeError: fetch failed] { cause: [Error: AggregateError] }
```

**Comment by DoraDong-2023** [comment]
Thanks for your attention! 

It seems weird that we have already contained `nltk.download('stopwords')` in `src/deploy/model.py` for downloading nltk data. This might due to another issue during docker building.

However, we have already now integrated 4 libs scanpy, squidpy, ehrapy, snapatac2 into one docker file, tested the docker image on our Linux server and pushed to dockerhub. We recommend you to have another try. If this error still exist, could have a try in `sudo docker exec -it [container_id] /bin/bash` and call `python` and install nltk stopword in it.

Let us know If the error still exists. Thanks!
